import { nature } from '@nature-ui/core';

export const El = {
  h1: nature('h1'),
  h2: nature('h2'),
  h3: nature('h3'),
  h4: nature('h4'),
  h5: nature('h5'),
  p: nature('p'),
  pre: nature('pre'),
  table: nature('table'),
  th: nature('th'),
  td: nature('td'),
  a: nature('a'),
  span: nature('span'),
  svg: nature('svg'),
  div: nature('div'),
  code: nature('code'),
  hr: nature('hr'),
  strong: nature('strong'),
  br: nature('br'),
  ul: nature('ul'),
  ol: nature('ol'),
  li: nature('li'),
  blockquote: nature('blockquote'),
};
